/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main.java
 *
 * Created on 2011-11-19, 15:00:29
 */

package kostkarubika;

import java.awt.Color;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Ja
 */
public class Main extends javax.swing.JFrame {

    /** Creates new form Main */
    public Main() {
        initComponents();        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FlipOver = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Scan = new javax.swing.JButton();
        OneXOne = new javax.swing.JTextField();
        OneXTwo = new javax.swing.JTextField();
        OneXThree = new javax.swing.JTextField();
        TwoXOne = new javax.swing.JTextField();
        TwoXTwo = new javax.swing.JTextField();
        TwoXThree = new javax.swing.JTextField();
        ThreeXOne = new javax.swing.JTextField();
        ThreeXTwo = new javax.swing.JTextField();
        ThreeXThree = new javax.swing.JTextField();
        Orientation = new javax.swing.JButton();
        Rotate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FlipOver.setText("Flip");
        FlipOver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FlipOverMouseClicked(evt);
            }
        });

        jButton3.setText("Pośrednik");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        Scan.setText("Scan");
        Scan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ScanMouseClicked(evt);
            }
        });

        OneXOne.setBackground(new java.awt.Color(204, 204, 255));
        OneXOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OneXOneActionPerformed(evt);
            }
        });

        OneXTwo.setBackground(new java.awt.Color(204, 204, 255));
        OneXTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OneXTwoActionPerformed(evt);
            }
        });

        OneXThree.setBackground(new java.awt.Color(204, 204, 255));
        OneXThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OneXThreeActionPerformed(evt);
            }
        });

        TwoXOne.setBackground(new java.awt.Color(204, 204, 255));
        TwoXOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoXOneActionPerformed(evt);
            }
        });

        TwoXTwo.setBackground(new java.awt.Color(204, 204, 255));
        TwoXTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoXTwoActionPerformed(evt);
            }
        });

        TwoXThree.setBackground(new java.awt.Color(204, 204, 255));
        TwoXThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoXThreeActionPerformed(evt);
            }
        });

        ThreeXOne.setBackground(new java.awt.Color(204, 204, 255));
        ThreeXOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThreeXOneActionPerformed(evt);
            }
        });

        ThreeXTwo.setBackground(new java.awt.Color(204, 204, 255));
        ThreeXTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThreeXTwoActionPerformed(evt);
            }
        });

        ThreeXThree.setBackground(new java.awt.Color(204, 204, 255));
        ThreeXThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThreeXThreeActionPerformed(evt);
            }
        });

        Orientation.setText("Orientation");
        Orientation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrientationMouseClicked(evt);
            }
        });

        Rotate.setText("Rotate");
        Rotate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RotateMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Rotate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Scan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FlipOver, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                            .addComponent(Orientation))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ThreeXOne, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ThreeXTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ThreeXThree, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(TwoXOne, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TwoXTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TwoXThree, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(OneXOne, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(OneXTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(OneXThree, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3)
                        .addGap(57, 57, 57)
                        .addComponent(FlipOver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Scan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Orientation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Rotate))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OneXTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OneXOne, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OneXThree, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TwoXOne, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TwoXTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TwoXThree, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ThreeXOne, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ThreeXTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ThreeXThree, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        final JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(jButton3);

        if (returnVal == JFileChooser.APPROVE_OPTION){
            File file = fc.getSelectedFile();
            //String string = file.getPath();

            String path = file.getParent();
            System.out.println("Sciezka: "+path);
            fileName = file.getName();
            System.out.println("Nazwa pliku: "+fileName.substring(0, fileName.lastIndexOf(".")));
            CommandLn.setPath(path);
            CommandLn.setFile(fileName.substring(0, fileName.lastIndexOf(".")));

        }
        //CommandLn.setPath("C:\\Documents and Settings\\Ja\\Moje dokumenty\\studia\\ZPI\\CommandToSocket\\src");
        //CommandLn.setFile("Main");
    }//GEN-LAST:event_jButton3MouseClicked

    private void FlipOverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlipOverMouseClicked
        Sterowanie.FlipOver();
    }//GEN-LAST:event_FlipOverMouseClicked

    private void ScanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScanMouseClicked
        String wynik[][] = Sterowanie.ReadColor();
        
        OneXOne.setBackground(Background(wynik[0][0]));
        OneXTwo.setBackground(Background(wynik[0][1]));
        OneXThree.setBackground(Background(wynik[0][2]));
        TwoXOne.setBackground(Background(wynik[1][0]));
        TwoXTwo.setBackground(Background(wynik[1][1]));
        TwoXThree.setBackground(Background(wynik[1][2]));
        ThreeXOne.setBackground(Background(wynik[2][0]));
        ThreeXTwo.setBackground(Background(wynik[2][1]));
        ThreeXThree.setBackground(Background(wynik[2][2]));
        
        for (int x=0;x<3;x++){
            for (int y=0; y<3;y++){
                System.out.print(wynik[x][y]+" ");
            }
        System.out.println();
        }
    }//GEN-LAST:event_ScanMouseClicked

    public static Color Background(String c){
        Color color = null;
        if (c.equals("RED"))
            color = Color.RED;
        if (c.equals("WHITE"))
            color = Color.WHITE;
        if (c.equals("BLUE"))
            color = Color.BLUE;
        if (c.equals("GREEN"))
            color = Color.GREEN;
        if (c.equals("YELLOW"))
            color = Color.YELLOW;
        return color;
    }

    private void OneXOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OneXOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OneXOneActionPerformed

    private void OneXTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OneXTwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OneXTwoActionPerformed

    private void OneXThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OneXThreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OneXThreeActionPerformed

    private void TwoXOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwoXOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TwoXOneActionPerformed

    private void TwoXTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwoXTwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TwoXTwoActionPerformed

    private void TwoXThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwoXThreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TwoXThreeActionPerformed

    private void ThreeXOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThreeXOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ThreeXOneActionPerformed

    private void ThreeXTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThreeXTwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ThreeXTwoActionPerformed

    private void ThreeXThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThreeXThreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ThreeXThreeActionPerformed

    private void OrientationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrientationMouseClicked
        Sterowanie.orientacjaKostki();
    }//GEN-LAST:event_OrientationMouseClicked

    private void RotateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RotateMouseClicked
        Sterowanie.rotateWall();
    }//GEN-LAST:event_RotateMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FlipOver;
    private javax.swing.JTextField OneXOne;
    private javax.swing.JTextField OneXThree;
    private javax.swing.JTextField OneXTwo;
    private javax.swing.JButton Orientation;
    private javax.swing.JButton Rotate;
    private javax.swing.JButton Scan;
    private javax.swing.JTextField ThreeXOne;
    private javax.swing.JTextField ThreeXThree;
    private javax.swing.JTextField ThreeXTwo;
    private javax.swing.JTextField TwoXOne;
    private javax.swing.JTextField TwoXThree;
    private javax.swing.JTextField TwoXTwo;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
    String fileName = "";
}
