
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import javax.swing.UIManager;



/**
 *
 * @author Ja
 */
public class Panel extends javax.swing.JFrame {

    /** Creates new form Panel */
    public Panel() {
        initComponents();
        jTextField1.setText("");
        jTextField2.setText("");

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Wyjscie1 = new javax.swing.JTextArea();
        wczytaj = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Wyjscie2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        Wyjscie3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        Wyjscie4 = new javax.swing.JTextArea();
        typeButtonTouch = new javax.swing.JToggleButton();
        wczytaj2 = new javax.swing.JButton();
        wczytaj3 = new javax.swing.JButton();
        wczytaj4 = new javax.swing.JButton();
        Clear2 = new javax.swing.JButton();
        Clear3 = new javax.swing.JButton();
        Clear4 = new javax.swing.JButton();
        typeButtonTouch2 = new javax.swing.JToggleButton();
        typeButtonTouch3 = new javax.swing.JToggleButton();
        typeButtonTouch4 = new javax.swing.JToggleButton();
        modeBox1 = new javax.swing.JComboBox();
        modeBox2 = new javax.swing.JComboBox();
        modeBox3 = new javax.swing.JComboBox();
        modeBox4 = new javax.swing.JComboBox();
        Reset1 = new javax.swing.JButton();
        Reset2 = new javax.swing.JButton();
        Reset3 = new javax.swing.JButton();
        Reset4 = new javax.swing.JButton();
        typeButtonSound1 = new javax.swing.JToggleButton();
        typeButtonSound2 = new javax.swing.JToggleButton();
        typeButtonSound3 = new javax.swing.JToggleButton();
        typeButtonSound4 = new javax.swing.JToggleButton();
        typeButtonLight1 = new javax.swing.JToggleButton();
        typeButtonLight2 = new javax.swing.JToggleButton();
        typeButtonLight3 = new javax.swing.JToggleButton();
        typeButtonLight4 = new javax.swing.JToggleButton();
        typeButtonUltrasonic1 = new javax.swing.JToggleButton();
        typeButtonUltrasonic2 = new javax.swing.JToggleButton();
        typeButtonUltrasonic3 = new javax.swing.JToggleButton();
        typeButtonUltrasonic4 = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tryb = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        mocSilnika = new javax.swing.JSlider();
        moc = new javax.swing.JTextField();
        stopButton = new javax.swing.JButton();
        leftButton = new javax.swing.JToggleButton();
        rightButton = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        sendCommandLine = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tryb1 = new javax.swing.JComboBox();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        mocSilnika1 = new javax.swing.JSlider();
        moc1 = new javax.swing.JTextField();
        stopButton1 = new javax.swing.JButton();
        leftButton1 = new javax.swing.JToggleButton();
        rightButton1 = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        tryb4 = new javax.swing.JComboBox();
        jTextField5 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        mocSilnika4 = new javax.swing.JSlider();
        moc4 = new javax.swing.JTextField();
        stopButton4 = new javax.swing.JButton();
        leftButton4 = new javax.swing.JToggleButton();
        rightButton4 = new javax.swing.JToggleButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sterowanie");

        Wyjscie1.setColumns(20);
        Wyjscie1.setRows(5);
        jScrollPane1.setViewportView(Wyjscie1);

        wczytaj.setText("Wczytaj");
        wczytaj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wczytajMouseClicked(evt);
            }
        });

        Clear.setText("Wyczyść");
        Clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearMouseClicked(evt);
            }
        });

        Wyjscie2.setColumns(20);
        Wyjscie2.setRows(5);
        jScrollPane2.setViewportView(Wyjscie2);

        Wyjscie3.setColumns(20);
        Wyjscie3.setRows(5);
        jScrollPane3.setViewportView(Wyjscie3);

        Wyjscie4.setColumns(20);
        Wyjscie4.setRows(5);
        jScrollPane4.setViewportView(Wyjscie4);

        typeButtonTouch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonTouch.png"))); // NOI18N
        typeButtonTouch.setBorder(null);
        typeButtonTouch.setMaximumSize(new java.awt.Dimension(50, 50));
        typeButtonTouch.setMinimumSize(new java.awt.Dimension(50, 50));
        typeButtonTouch.setPreferredSize(new java.awt.Dimension(50, 50));
        typeButtonTouch.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typeButtonTouchItemStateChanged(evt);
            }
        });
        typeButtonTouch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeButtonTouchActionPerformed(evt);
            }
        });

        wczytaj2.setText("Wczytaj");
        wczytaj2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wczytaj2MouseClicked(evt);
            }
        });

        wczytaj3.setText("Wczytaj");
        wczytaj3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wczytaj3MouseClicked(evt);
            }
        });

        wczytaj4.setText("Wczytaj");
        wczytaj4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wczytaj4MouseClicked(evt);
            }
        });

        Clear2.setText("Wyczyść");
        Clear2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Clear2MouseClicked(evt);
            }
        });

        Clear3.setText("Wyczyść");
        Clear3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Clear3MouseClicked(evt);
            }
        });

        Clear4.setText("Wyczyść");
        Clear4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Clear4MouseClicked(evt);
            }
        });

        typeButtonTouch2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonTouch.png"))); // NOI18N
        typeButtonTouch2.setBorder(null);
        typeButtonTouch2.setMaximumSize(new java.awt.Dimension(50, 50));
        typeButtonTouch2.setMinimumSize(new java.awt.Dimension(50, 50));
        typeButtonTouch2.setPreferredSize(new java.awt.Dimension(50, 50));
        typeButtonTouch2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typeButtonTouch2ItemStateChanged(evt);
            }
        });
        typeButtonTouch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeButtonTouch2ActionPerformed(evt);
            }
        });

        typeButtonTouch3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonTouch.png"))); // NOI18N
        typeButtonTouch3.setBorder(null);
        typeButtonTouch3.setMaximumSize(new java.awt.Dimension(50, 50));
        typeButtonTouch3.setMinimumSize(new java.awt.Dimension(50, 50));
        typeButtonTouch3.setPreferredSize(new java.awt.Dimension(50, 50));
        typeButtonTouch3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typeButtonTouch3ItemStateChanged(evt);
            }
        });
        typeButtonTouch3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeButtonTouch3ActionPerformed(evt);
            }
        });

        typeButtonTouch4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonTouch.png"))); // NOI18N
        typeButtonTouch4.setBorder(null);
        typeButtonTouch4.setMaximumSize(new java.awt.Dimension(50, 50));
        typeButtonTouch4.setMinimumSize(new java.awt.Dimension(50, 50));
        typeButtonTouch4.setPreferredSize(new java.awt.Dimension(50, 50));
        typeButtonTouch4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typeButtonTouch4ItemStateChanged(evt);
            }
        });
        typeButtonTouch4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeButtonTouch4ActionPerformed(evt);
            }
        });

        modeBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "raw", "bool", "switch", "periodic", "percent" }));

        modeBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "raw", "bool", "switch", "periodic", "percent" }));

        modeBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "raw", "bool", "switch", "periodic", "percent" }));

        modeBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "raw", "bool", "switch", "periodic", "percent" }));

        Reset1.setText("Reset");
        Reset1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Reset1MouseClicked(evt);
            }
        });

        Reset2.setText("Reset");
        Reset2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Reset2MouseClicked(evt);
            }
        });

        Reset3.setText("Reset");
        Reset3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Reset3MouseClicked(evt);
            }
        });

        Reset4.setText("Reset");
        Reset4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Reset4MouseClicked(evt);
            }
        });

        typeButtonSound1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonSound.png"))); // NOI18N
        typeButtonSound1.setMaximumSize(new java.awt.Dimension(50, 50));
        typeButtonSound1.setMinimumSize(new java.awt.Dimension(50, 50));
        typeButtonSound1.setPreferredSize(new java.awt.Dimension(50, 50));
        typeButtonSound1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typeButtonSound1ItemStateChanged(evt);
            }
        });

        typeButtonSound2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonSound.png"))); // NOI18N
        typeButtonSound2.setMaximumSize(new java.awt.Dimension(50, 50));
        typeButtonSound2.setMinimumSize(new java.awt.Dimension(50, 50));
        typeButtonSound2.setPreferredSize(new java.awt.Dimension(50, 50));
        typeButtonSound2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typeButtonSound2ItemStateChanged(evt);
            }
        });

        typeButtonSound3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonSound.png"))); // NOI18N
        typeButtonSound3.setMaximumSize(new java.awt.Dimension(50, 50));
        typeButtonSound3.setMinimumSize(new java.awt.Dimension(50, 50));
        typeButtonSound3.setPreferredSize(new java.awt.Dimension(50, 50));
        typeButtonSound3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typeButtonSound3ItemStateChanged(evt);
            }
        });

        typeButtonSound4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonSound.png"))); // NOI18N
        typeButtonSound4.setMaximumSize(new java.awt.Dimension(50, 50));
        typeButtonSound4.setMinimumSize(new java.awt.Dimension(50, 50));
        typeButtonSound4.setPreferredSize(new java.awt.Dimension(50, 50));
        typeButtonSound4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typeButtonSound4ItemStateChanged(evt);
            }
        });

        typeButtonLight1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonLight.png"))); // NOI18N
        typeButtonLight1.setMaximumSize(new java.awt.Dimension(50, 50));
        typeButtonLight1.setMinimumSize(new java.awt.Dimension(50, 50));
        typeButtonLight1.setPreferredSize(new java.awt.Dimension(50, 50));
        typeButtonLight1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typeButtonLight1ItemStateChanged(evt);
            }
        });

        typeButtonLight2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonLight.png"))); // NOI18N
        typeButtonLight2.setMaximumSize(new java.awt.Dimension(50, 50));
        typeButtonLight2.setMinimumSize(new java.awt.Dimension(50, 50));
        typeButtonLight2.setPreferredSize(new java.awt.Dimension(50, 50));
        typeButtonLight2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typeButtonLight2ItemStateChanged(evt);
            }
        });

        typeButtonLight3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonLight.png"))); // NOI18N
        typeButtonLight3.setMaximumSize(new java.awt.Dimension(50, 50));
        typeButtonLight3.setMinimumSize(new java.awt.Dimension(50, 50));
        typeButtonLight3.setPreferredSize(new java.awt.Dimension(50, 50));
        typeButtonLight3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typeButtonLight3ItemStateChanged(evt);
            }
        });

        typeButtonLight4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonLight.png"))); // NOI18N
        typeButtonLight4.setMaximumSize(new java.awt.Dimension(50, 50));
        typeButtonLight4.setMinimumSize(new java.awt.Dimension(50, 50));
        typeButtonLight4.setPreferredSize(new java.awt.Dimension(50, 50));
        typeButtonLight4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typeButtonLight4ItemStateChanged(evt);
            }
        });

        typeButtonUltrasonic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonUltrasonic.png"))); // NOI18N
        typeButtonUltrasonic1.setMaximumSize(new java.awt.Dimension(50, 50));
        typeButtonUltrasonic1.setMinimumSize(new java.awt.Dimension(50, 50));
        typeButtonUltrasonic1.setPreferredSize(new java.awt.Dimension(50, 50));
        typeButtonUltrasonic1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typeButtonUltrasonic1ItemStateChanged(evt);
            }
        });

        typeButtonUltrasonic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonUltrasonic.png"))); // NOI18N
        typeButtonUltrasonic2.setMaximumSize(new java.awt.Dimension(50, 50));
        typeButtonUltrasonic2.setMinimumSize(new java.awt.Dimension(50, 50));
        typeButtonUltrasonic2.setPreferredSize(new java.awt.Dimension(50, 50));
        typeButtonUltrasonic2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typeButtonUltrasonic2ItemStateChanged(evt);
            }
        });

        typeButtonUltrasonic3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonUltrasonic.png"))); // NOI18N
        typeButtonUltrasonic3.setMaximumSize(new java.awt.Dimension(50, 50));
        typeButtonUltrasonic3.setMinimumSize(new java.awt.Dimension(50, 50));
        typeButtonUltrasonic3.setPreferredSize(new java.awt.Dimension(50, 50));
        typeButtonUltrasonic3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typeButtonUltrasonic3ItemStateChanged(evt);
            }
        });

        typeButtonUltrasonic4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonUltrasonic.png"))); // NOI18N
        typeButtonUltrasonic4.setMaximumSize(new java.awt.Dimension(50, 50));
        typeButtonUltrasonic4.setMinimumSize(new java.awt.Dimension(50, 50));
        typeButtonUltrasonic4.setPreferredSize(new java.awt.Dimension(50, 50));
        typeButtonUltrasonic4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typeButtonUltrasonic4ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wczytaj, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(typeButtonSound1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(typeButtonTouch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Reset1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(modeBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Clear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(typeButtonLight1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(typeButtonUltrasonic1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wczytaj2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modeBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Reset2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Clear2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(typeButtonSound2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(typeButtonTouch2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(typeButtonLight2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(typeButtonUltrasonic2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wczytaj3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modeBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Reset3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Clear3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(typeButtonSound3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(typeButtonTouch3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(typeButtonLight3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(typeButtonUltrasonic3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modeBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wczytaj4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Reset4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Clear4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(typeButtonSound4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(typeButtonTouch4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(typeButtonLight4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(typeButtonUltrasonic4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(632, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wczytaj)
                    .addComponent(wczytaj2)
                    .addComponent(wczytaj3)
                    .addComponent(wczytaj4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(typeButtonTouch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeButtonTouch2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeButtonTouch3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeButtonTouch4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typeButtonSound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeButtonSound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeButtonSound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeButtonSound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(typeButtonLight1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typeButtonLight2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(typeButtonUltrasonic2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typeButtonUltrasonic1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(typeButtonLight3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(typeButtonUltrasonic3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(typeButtonLight4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(typeButtonUltrasonic4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modeBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modeBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modeBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modeBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Clear)
                    .addComponent(Clear2)
                    .addComponent(Clear3)
                    .addComponent(Clear4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Reset1)
                    .addComponent(Reset2)
                    .addComponent(Reset3)
                    .addComponent(Reset4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel2.setText("Obrót o");

        tryb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "kąt", "liczbę obrotów", "czas" }));

        jTextField1.setText("jTextField1");

        jButton1.setText("Wykonaj");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        mocSilnika.setMajorTickSpacing(25);
        mocSilnika.setMinimum(-100);
        mocSilnika.setPaintTicks(true);
        mocSilnika.setValue(70);
        mocSilnika.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mocSilnikaStateChanged(evt);
            }
        });

        moc.setText("70");
        moc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mocKeyTyped(evt);
            }
        });

        stopButton.setText("Stop");
        stopButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stopButtonMouseClicked(evt);
            }
        });

        leftButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-left-blue.png"))); // NOI18N
        leftButton.setPreferredSize(new java.awt.Dimension(30, 40));
        leftButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                leftButtonItemStateChanged(evt);
            }
        });
        leftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftButtonActionPerformed(evt);
            }
        });

        rightButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-right-blue.png"))); // NOI18N
        rightButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rightButtonItemStateChanged(evt);
            }
        });

        jLabel3.setText("Moc silnika:");

        jLabel6.setText("Silnik B");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(leftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(tryb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(mocSilnika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(moc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(rightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(stopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tryb, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(moc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mocSilnika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(leftButton, 0, 0, Short.MAX_VALUE)
                            .addComponent(rightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stopButton)
                .addGap(66, 66, 66))
        );

        sendCommandLine.setText("sendCommandLine");
        sendCommandLine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendCommandLineMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(sendCommandLine)
                .addContainerGap(961, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sendCommandLine)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setToolTipText("");
        jPanel5.setName(""); // NOI18N

        jLabel4.setText("Obrót o");

        tryb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "kąt", "liczbę obrotów", "czas" }));

        jTextField2.setText("jTextField1");

        jButton2.setText("Wykonaj");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        mocSilnika1.setMajorTickSpacing(25);
        mocSilnika1.setMinimum(-100);
        mocSilnika1.setPaintTicks(true);
        mocSilnika1.setValue(70);
        mocSilnika1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mocSilnika1StateChanged(evt);
            }
        });

        moc1.setText("70");
        moc1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                moc1KeyTyped(evt);
            }
        });

        stopButton1.setText("Stop");
        stopButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stopButton1MouseClicked(evt);
            }
        });

        leftButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-left-blue.png"))); // NOI18N
        leftButton1.setPreferredSize(new java.awt.Dimension(30, 40));
        leftButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                leftButton1ItemStateChanged(evt);
            }
        });
        leftButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftButton1ActionPerformed(evt);
            }
        });

        rightButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-right-blue.png"))); // NOI18N
        rightButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rightButton1ItemStateChanged(evt);
            }
        });

        jLabel5.setText("Moc silnika:");

        jLabel1.setText("Silnik A");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(leftButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(tryb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(mocSilnika1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(moc1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(rightButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(stopButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tryb1, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jButton2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(moc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mocSilnika1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(leftButton1, 0, 0, Short.MAX_VALUE)
                            .addComponent(rightButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stopButton1)
                .addGap(66, 66, 66))
        );

        jLabel13.setText("Obrót o");

        tryb4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "kąt", "liczbę obrotów", "czas" }));

        jTextField5.setText("jTextField1");

        jButton5.setText("Wykonaj");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        mocSilnika4.setMajorTickSpacing(25);
        mocSilnika4.setMinimum(-100);
        mocSilnika4.setPaintTicks(true);
        mocSilnika4.setValue(70);
        mocSilnika4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mocSilnika4StateChanged(evt);
            }
        });

        moc4.setText("70");
        moc4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                moc4KeyTyped(evt);
            }
        });

        stopButton4.setText("Stop");
        stopButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stopButton4MouseClicked(evt);
            }
        });

        leftButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-left-blue.png"))); // NOI18N
        leftButton4.setPreferredSize(new java.awt.Dimension(30, 40));
        leftButton4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                leftButton4ItemStateChanged(evt);
            }
        });
        leftButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftButton4ActionPerformed(evt);
            }
        });

        rightButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-right-blue.png"))); // NOI18N
        rightButton4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rightButton4ItemStateChanged(evt);
            }
        });

        jLabel14.setText("Moc silnika:");

        jLabel15.setText("Silnik C");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addComponent(leftButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(tryb4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(mocSilnika4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(moc4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(rightButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(stopButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addGap(19, 19, 19)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tryb4, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jButton5)))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(moc4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mocSilnika4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(leftButton4, 0, 0, Short.MAX_VALUE)
                            .addComponent(rightButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stopButton4)
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jPanel5.getAccessibleContext().setAccessibleDescription("null");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wczytajMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wczytajMouseClicked
        Czujniki.setSensorMode(modeBox1.getSelectedIndex());
        String tekst = Czujniki.readSensor();        
        Wyjscie1.append(tekst+"\n");
}//GEN-LAST:event_wczytajMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        int y = 0;
        int x = 0;
        int z = -1;
        int q = 0;
        q = mocSilnika.getValue();
        z = tryb.getSelectedIndex();
        x = 2;
        try{
            y = Integer.parseInt(jTextField1.getText());
        } catch(Exception e){
            System.out.println("Zły typ danych");
        }        
        Sterowanie.makeObrot(x, y, z, q);
}//GEN-LAST:event_jButton1MouseClicked

    private void ClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearMouseClicked
        Wyjscie1.setText("");
    }//GEN-LAST:event_ClearMouseClicked

    private void mocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mocKeyTyped
        if (moc.getText().compareTo("") != 0) {
            try {
                mocSilnika.setValue(Integer.parseInt(moc.getText()));
            }
            catch(NumberFormatException e){
                System.out.println("Liczbe wpisz, gupku :P");
            }
        }
    }//GEN-LAST:event_mocKeyTyped

    private void mocSilnikaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mocSilnikaStateChanged
        moc.setText(Integer.toString(mocSilnika.getValue()));
    }//GEN-LAST:event_mocSilnikaStateChanged

    private void leftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leftButtonActionPerformed

    private void leftButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_leftButtonItemStateChanged
        if (evt.getStateChange() == 1){
        int x = 2;
        int q = mocSilnika.getValue();
        Sterowanie.leftTurn(x,q);
        rightButton.setSelected(false);
        }
    }//GEN-LAST:event_leftButtonItemStateChanged

    private void rightButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rightButtonItemStateChanged
        if (evt.getStateChange() == 1){
        int x = 2;
        int q = mocSilnika.getValue();
        Sterowanie.rightTurn(x,q);
        leftButton.setSelected(false);
        }
    }//GEN-LAST:event_rightButtonItemStateChanged

    private void stopButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopButtonMouseClicked
        Sterowanie.engineStop(2);
    }//GEN-LAST:event_stopButtonMouseClicked

    private void typeButtonTouchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeButtonTouchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeButtonTouchActionPerformed

    private void typeButtonTouchItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeButtonTouchItemStateChanged
        if (evt.getStateChange() == 1){
        Czujniki.setSensor(1);
        Czujniki.setSensorType(1);}
        else Czujniki.setSensor(-1);
    }//GEN-LAST:event_typeButtonTouchItemStateChanged

    private void wczytaj2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wczytaj2MouseClicked
        Czujniki.setSensorMode(modeBox2.getSelectedIndex());
        String tekst = Czujniki.readSensor();
        Wyjscie2.append(tekst+"\n");
    }//GEN-LAST:event_wczytaj2MouseClicked

    private void wczytaj3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wczytaj3MouseClicked
        Czujniki.setSensorMode(modeBox3.getSelectedIndex());
        String tekst = Czujniki.readSensor();
        Wyjscie3.append(tekst+"\n");
    }//GEN-LAST:event_wczytaj3MouseClicked

    private void wczytaj4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wczytaj4MouseClicked
        Czujniki.setSensorMode(modeBox4.getSelectedIndex());
        String tekst = Czujniki.readSensor();
        Wyjscie4.append(tekst+"\n");
    }//GEN-LAST:event_wczytaj4MouseClicked

    private void Clear2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Clear2MouseClicked
        Wyjscie2.setText("");
    }//GEN-LAST:event_Clear2MouseClicked

    private void Clear3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Clear3MouseClicked
        Wyjscie3.setText("");
    }//GEN-LAST:event_Clear3MouseClicked

    private void Clear4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Clear4MouseClicked
        Wyjscie4.setText("");
    }//GEN-LAST:event_Clear4MouseClicked

    private void typeButtonTouch2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeButtonTouch2ItemStateChanged
        if (evt.getStateChange() == 1){
        Czujniki.setSensor(2);
        Czujniki.setSensorType(1);}
        else Czujniki.setSensor(-1);
    }//GEN-LAST:event_typeButtonTouch2ItemStateChanged

    private void typeButtonTouch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeButtonTouch2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeButtonTouch2ActionPerformed

    private void typeButtonTouch3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeButtonTouch3ItemStateChanged
        if (evt.getStateChange() == 1){
        Czujniki.setSensor(3);
        Czujniki.setSensorType(1);}
        else Czujniki.setSensor(-1);
    }//GEN-LAST:event_typeButtonTouch3ItemStateChanged

    private void typeButtonTouch3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeButtonTouch3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeButtonTouch3ActionPerformed

    private void typeButtonTouch4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeButtonTouch4ItemStateChanged
        if (evt.getStateChange() == 1){
        Czujniki.setSensor(4);
        Czujniki.setSensorType(1);}
        else Czujniki.setSensor(-1);
    }//GEN-LAST:event_typeButtonTouch4ItemStateChanged

    private void typeButtonTouch4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeButtonTouch4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeButtonTouch4ActionPerformed

    private void Reset1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Reset1MouseClicked
        Czujniki.resetSensor(1);
    }//GEN-LAST:event_Reset1MouseClicked

    private void Reset2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Reset2MouseClicked
        Czujniki.resetSensor(2);
    }//GEN-LAST:event_Reset2MouseClicked

    private void Reset3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Reset3MouseClicked
        Czujniki.resetSensor(3);
    }//GEN-LAST:event_Reset3MouseClicked

    private void Reset4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Reset4MouseClicked
        Czujniki.resetSensor(4);
    }//GEN-LAST:event_Reset4MouseClicked

    private void typeButtonSound1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeButtonSound1ItemStateChanged
        if (evt.getStateChange() == 1){
        Czujniki.setSensor(1);
        Czujniki.setSensorType(2);}
        else Czujniki.setSensor(-1);
    }//GEN-LAST:event_typeButtonSound1ItemStateChanged

    private void typeButtonSound2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeButtonSound2ItemStateChanged
        if (evt.getStateChange() == 1){
        Czujniki.setSensor(2);
        Czujniki.setSensorType(2);}
        else Czujniki.setSensor(-1);
    }//GEN-LAST:event_typeButtonSound2ItemStateChanged

    private void typeButtonSound3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeButtonSound3ItemStateChanged
        if (evt.getStateChange() == 1){
        Czujniki.setSensor(3);
        Czujniki.setSensorType(2);}
        else Czujniki.setSensor(-1);
    }//GEN-LAST:event_typeButtonSound3ItemStateChanged

    private void typeButtonSound4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeButtonSound4ItemStateChanged
        if (evt.getStateChange() == 1){
        Czujniki.setSensor(4);
        Czujniki.setSensorType(2);}
        else Czujniki.setSensor(-1);
    }//GEN-LAST:event_typeButtonSound4ItemStateChanged

    private void typeButtonLight1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeButtonLight1ItemStateChanged
        if (evt.getStateChange() == 1){
        Czujniki.setSensor(1);
        Czujniki.setSensorType(3);}
        else Czujniki.setSensor(-1);
    }//GEN-LAST:event_typeButtonLight1ItemStateChanged

    private void typeButtonLight2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeButtonLight2ItemStateChanged
        if (evt.getStateChange() == 1){
        Czujniki.setSensor(2);
        Czujniki.setSensorType(3);}
        else Czujniki.setSensor(-1);
    }//GEN-LAST:event_typeButtonLight2ItemStateChanged

    private void typeButtonLight3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeButtonLight3ItemStateChanged
        if (evt.getStateChange() == 1){
        Czujniki.setSensor(3);
        Czujniki.setSensorType(3);}
        else Czujniki.setSensor(-1);
    }//GEN-LAST:event_typeButtonLight3ItemStateChanged

    private void typeButtonLight4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeButtonLight4ItemStateChanged
        if (evt.getStateChange() == 1){
        Czujniki.setSensor(4);
        Czujniki.setSensorType(3);}
        else Czujniki.setSensor(-1);
    }//GEN-LAST:event_typeButtonLight4ItemStateChanged

    private void typeButtonUltrasonic1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeButtonUltrasonic1ItemStateChanged
        if (evt.getStateChange() == 1){
        Czujniki.setSensor(1);
        Czujniki.setSensorType(4);}
        else Czujniki.setSensor(-1);
    }//GEN-LAST:event_typeButtonUltrasonic1ItemStateChanged

    private void typeButtonUltrasonic2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeButtonUltrasonic2ItemStateChanged
        if (evt.getStateChange() == 1){
        Czujniki.setSensor(2);
        Czujniki.setSensorType(4);}
        else Czujniki.setSensor(-1);
    }//GEN-LAST:event_typeButtonUltrasonic2ItemStateChanged

    private void typeButtonUltrasonic3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeButtonUltrasonic3ItemStateChanged
        if (evt.getStateChange() == 1){
        Czujniki.setSensor(3);
        Czujniki.setSensorType(4);}
        else Czujniki.setSensor(-1);
    }//GEN-LAST:event_typeButtonUltrasonic3ItemStateChanged

    private void typeButtonUltrasonic4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeButtonUltrasonic4ItemStateChanged
        if (evt.getStateChange() == 1){
        Czujniki.setSensor(4);
        Czujniki.setSensorType(4);}
        else Czujniki.setSensor(-1);
    }//GEN-LAST:event_typeButtonUltrasonic4ItemStateChanged

    private void sendCommandLineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendCommandLineMouseClicked
        CommandLn.CommandLn();
    }//GEN-LAST:event_sendCommandLineMouseClicked

    private void rightButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rightButton1ItemStateChanged
        if (evt.getStateChange() == 1){
            int x = 1;
            int q = mocSilnika1.getValue();
            Sterowanie.rightTurn(x,q);
            leftButton1.setSelected(false);
        }
}//GEN-LAST:event_rightButton1ItemStateChanged

    private void leftButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftButton1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_leftButton1ActionPerformed

    private void leftButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_leftButton1ItemStateChanged
        if (evt.getStateChange() == 1){
            int x = 1;
            int q = mocSilnika1.getValue();
            Sterowanie.leftTurn(x,q);
            rightButton1.setSelected(false);
        }
}//GEN-LAST:event_leftButton1ItemStateChanged

    private void stopButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopButton1MouseClicked
        Sterowanie.engineStop(1);
}//GEN-LAST:event_stopButton1MouseClicked

    private void moc1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_moc1KeyTyped
        if (moc1.getText().compareTo("") != 0) {
            try {
                mocSilnika1.setValue(Integer.parseInt(moc1.getText()));
            } catch(NumberFormatException e){
                System.out.println("Liczbe wpisz");
            }
        }
}//GEN-LAST:event_moc1KeyTyped

    private void mocSilnika1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mocSilnika1StateChanged
        moc1.setText(Integer.toString(mocSilnika1.getValue()));
}//GEN-LAST:event_mocSilnika1StateChanged

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        int y = 0;
        int x = 0;
        int z = -1;
        int q = 0;
        q = mocSilnika1.getValue();
        z = tryb1.getSelectedIndex();
        x = 1;
        try{
            y = Integer.parseInt(jTextField2.getText());
        } catch(Exception e){
            System.out.println("Zły typ danych");
        }
        Sterowanie.makeObrot(x, y, z, q);
}//GEN-LAST:event_jButton2MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        int y = 0;
        int x = 0;
        int z = -1;
        int q = 0;
        q = mocSilnika2.getValue();
        z = tryb2.getSelectedIndex();
        x = 3;
        try{
            y = Integer.parseInt(jTextField3.getText());
        } catch(Exception e){
            System.out.println("Zły typ danych");
        }
        Sterowanie.makeObrot(x, y, z, q);
    }//GEN-LAST:event_jButton5MouseClicked

    private void mocSilnika4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mocSilnika4StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_mocSilnika4StateChanged

    private void moc4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_moc4KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_moc4KeyTyped

    private void stopButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopButton4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_stopButton4MouseClicked

    private void leftButton4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_leftButton4ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_leftButton4ItemStateChanged

    private void leftButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leftButton4ActionPerformed

    private void rightButton4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rightButton4ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_rightButton4ItemStateChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {

        try{
          UIManager.setLookAndFeel(
            UIManager.getSystemLookAndFeelClassName());

         }
        catch(Exception e){
            System.out.println("Nimbus isn't available");
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton Clear2;
    private javax.swing.JButton Clear3;
    private javax.swing.JButton Clear4;
    private javax.swing.JButton Reset1;
    private javax.swing.JButton Reset2;
    private javax.swing.JButton Reset3;
    private javax.swing.JButton Reset4;
    private javax.swing.JTextArea Wyjscie1;
    private javax.swing.JTextArea Wyjscie2;
    private javax.swing.JTextArea Wyjscie3;
    private javax.swing.JTextArea Wyjscie4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JToggleButton leftButton;
    private javax.swing.JToggleButton leftButton1;
    private javax.swing.JToggleButton leftButton2;
    private javax.swing.JToggleButton leftButton3;
    private javax.swing.JToggleButton leftButton4;
    private javax.swing.JTextField moc;
    private javax.swing.JTextField moc1;
    private javax.swing.JTextField moc2;
    private javax.swing.JTextField moc3;
    private javax.swing.JTextField moc4;
    private javax.swing.JSlider mocSilnika;
    private javax.swing.JSlider mocSilnika1;
    private javax.swing.JSlider mocSilnika2;
    private javax.swing.JSlider mocSilnika3;
    private javax.swing.JSlider mocSilnika4;
    private javax.swing.JComboBox modeBox1;
    private javax.swing.JComboBox modeBox2;
    private javax.swing.JComboBox modeBox3;
    private javax.swing.JComboBox modeBox4;
    private javax.swing.JToggleButton rightButton;
    private javax.swing.JToggleButton rightButton1;
    private javax.swing.JToggleButton rightButton2;
    private javax.swing.JToggleButton rightButton3;
    private javax.swing.JToggleButton rightButton4;
    private javax.swing.JButton sendCommandLine;
    private javax.swing.JButton stopButton;
    private javax.swing.JButton stopButton1;
    private javax.swing.JButton stopButton2;
    private javax.swing.JButton stopButton3;
    private javax.swing.JButton stopButton4;
    private javax.swing.JComboBox tryb;
    private javax.swing.JComboBox tryb1;
    private javax.swing.JComboBox tryb2;
    private javax.swing.JComboBox tryb3;
    private javax.swing.JComboBox tryb4;
    private javax.swing.JToggleButton typeButtonLight1;
    private javax.swing.JToggleButton typeButtonLight2;
    private javax.swing.JToggleButton typeButtonLight3;
    private javax.swing.JToggleButton typeButtonLight4;
    private javax.swing.JToggleButton typeButtonSound1;
    private javax.swing.JToggleButton typeButtonSound2;
    private javax.swing.JToggleButton typeButtonSound3;
    private javax.swing.JToggleButton typeButtonSound4;
    private javax.swing.JToggleButton typeButtonTouch;
    private javax.swing.JToggleButton typeButtonTouch2;
    private javax.swing.JToggleButton typeButtonTouch3;
    private javax.swing.JToggleButton typeButtonTouch4;
    private javax.swing.JToggleButton typeButtonUltrasonic1;
    private javax.swing.JToggleButton typeButtonUltrasonic2;
    private javax.swing.JToggleButton typeButtonUltrasonic3;
    private javax.swing.JToggleButton typeButtonUltrasonic4;
    private javax.swing.JButton wczytaj;
    private javax.swing.JButton wczytaj2;
    private javax.swing.JButton wczytaj3;
    private javax.swing.JButton wczytaj4;
    // End of variables declaration//GEN-END:variables
    int silnik = -1;
    int type = -1;
}
